INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R1', 'sgsdg');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R2', 'sdgsgsgsdgs');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R3', 'ssfy5eevcgdf');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R4', 'dhdhvb sdgs s s sd ');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R5', 'gsdfs sadfs fsd sdf sd');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R6', 'dgsdfg sfs fs sf sdf dfsf');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R7', 'dgdg sdsd sdf sdf s');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R8', 'sfsjks sdfksdfnksf sdfsld');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R9', 'sfdsof asfsdf sdgfhgfhs');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R10', 'sfsdfsd sfsdfsdf sfsd fsd ');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R11', 'sfsdf gdoijn0erenc ');
INSERT INTO `pp_indust`.`resource` (`name`, `description`) VALUES ('R12', 'sdf4werwe rwe werwerwe ');
commit;